# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: dcttechnology
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-job-queue-system
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  environment:
    QUEUE_URL:
      Ref: JobQueue

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  
  createJob:
    handler: handler.createJob
    events:
      - httpApi:
          path: /job
          method: post

  worker:
    handler: handler.worker
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - JobQueue
              - Arn

resources:
  Resources:
    JobQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: job-queue

    JobsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: jobs
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: jobId
            AttributeType: S
        KeySchema:
          - AttributeName: jobId
            KeyType: HASH