org: dcttechnology
service: serverless-job-queue-system
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  stage: ${opt:stage, 'dev'}

  environment:
    QUEUE_URL:
      Ref: JobQueue
    STAGE: ${self:provider.stage}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
          Resource:
            - Fn::GetAtt: [JobsTable, Arn]

        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource:
            - Fn::GetAtt: [JobQueue, Arn]

functions:
  createJob:
    handler: handler.createJob
    events:
      - httpApi:
          path: /job
          method: post

  getJob:
    handler: handler.getJob
    events:
      - httpApi:
          path: /job/{id}
          method: get

  worker:
    handler: handler.worker
    timeout: 60
    reservedConcurrency: 5
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - JobQueue
              - Arn

resources:
  Resources:

    JobDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: job-dlq-${self:provider.stage}

    JobQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: job-queue-${self:provider.stage}
        VisibilityTimeout: 70
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - JobDLQ
              - Arn
          maxReceiveCount: 3

    JobsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: jobs-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: jobId
            AttributeType: S
        KeySchema:
          - AttributeName: jobId
            KeyType: HASH